set_property PACKAGE_PIN Y18 [get_ports clk_i]
set_property PACKAGE_PIN P20 [get_ports rst_i]
set_property PACKAGE_PIN C19 [get_ports led_en[0]]
set_property PACKAGE_PIN E19 [get_ports led_en[1]]
set_property PACKAGE_PIN D19 [get_ports led_en[2]]
set_property PACKAGE_PIN F18 [get_ports led_en[3]]
set_property PACKAGE_PIN E18 [get_ports led_en[4]]
set_property PACKAGE_PIN B20 [get_ports led_en[5]]
set_property PACKAGE_PIN A20 [get_ports led_en[6]]
set_property PACKAGE_PIN A18 [get_ports led_en[7]]

set_property PACKAGE_PIN F15 [get_ports led_ca_o]
set_property PACKAGE_PIN F13 [get_ports led_cb_o]
set_property PACKAGE_PIN F14 [get_ports led_cc_o]
set_property PACKAGE_PIN F16 [get_ports led_cd_o]
set_property PACKAGE_PIN E17 [get_ports led_ce_o]
set_property PACKAGE_PIN C14 [get_ports led_cf_o]
set_property PACKAGE_PIN C15 [get_ports led_cg_o]
set_property PACKAGE_PIN E13 [get_ports led_dp_o]


set_property PACKAGE_PIN W4 [get_ports switches_i[0]]
set_property PACKAGE_PIN R4 [get_ports switches_i[1]]
set_property PACKAGE_PIN T4 [get_ports switches_i[2]]
set_property PACKAGE_PIN T5 [get_ports switches_i[3]]
set_property PACKAGE_PIN U5 [get_ports switches_i[4]]
set_property PACKAGE_PIN W6 [get_ports switches_i[5]]
set_property PACKAGE_PIN W5 [get_ports switches_i[6]]
set_property PACKAGE_PIN U6 [get_ports switches_i[7]]
set_property PACKAGE_PIN V5 [get_ports switches_i[8]]
set_property PACKAGE_PIN R6 [get_ports switches_i[9]]
set_property PACKAGE_PIN T6 [get_ports switches_i[10]]
set_property PACKAGE_PIN Y6 [get_ports switches_i[11]]
set_property PACKAGE_PIN AA6 [get_ports switches_i[12]]
set_property PACKAGE_PIN V7 [get_ports switches_i[13]]
set_property PACKAGE_PIN AB7 [get_ports switches_i[14]]
set_property PACKAGE_PIN AB6 [get_ports switches_i[15]]
set_property PACKAGE_PIN V9 [get_ports switches_i[16]]
set_property PACKAGE_PIN V8 [get_ports switches_i[17]]
set_property PACKAGE_PIN AA8 [get_ports switches_i[18]]
set_property PACKAGE_PIN AB8 [get_ports switches_i[19]]
set_property PACKAGE_PIN Y8 [get_ports switches_i[20]]
set_property PACKAGE_PIN Y7 [get_ports switches_i[21]]
set_property PACKAGE_PIN W9 [get_ports switches_i[22]]
set_property PACKAGE_PIN Y9 [get_ports switches_i[23]]


set_property PACKAGE_PIN A21 [get_ports leds_o[0]]
set_property PACKAGE_PIN E22 [get_ports leds_o[1]]
set_property PACKAGE_PIN D22 [get_ports leds_o[2]]
set_property PACKAGE_PIN E21 [get_ports leds_o[3]]
set_property PACKAGE_PIN D21 [get_ports leds_o[4]]
set_property PACKAGE_PIN G21 [get_ports leds_o[5]]
set_property PACKAGE_PIN G22 [get_ports leds_o[6]]
set_property PACKAGE_PIN F21 [get_ports leds_o[7]]
set_property PACKAGE_PIN J17 [get_ports leds_o[8]]
set_property PACKAGE_PIN L14 [get_ports leds_o[9]]
set_property PACKAGE_PIN L15 [get_ports leds_o[10]]
set_property PACKAGE_PIN L16 [get_ports leds_o[11]]
set_property PACKAGE_PIN K16 [get_ports leds_o[12]]
set_property PACKAGE_PIN M15 [get_ports leds_o[13]]
set_property PACKAGE_PIN M16 [get_ports leds_o[14]]
set_property PACKAGE_PIN M17 [get_ports leds_o[15]]
set_property PACKAGE_PIN N19 [get_ports leds_o[16]]
set_property PACKAGE_PIN N20 [get_ports leds_o[17]]
set_property PACKAGE_PIN M20 [get_ports leds_o[18]]
set_property PACKAGE_PIN K13 [get_ports leds_o[19]]
set_property PACKAGE_PIN K14 [get_ports leds_o[20]]
set_property PACKAGE_PIN M13 [get_ports leds_o[21]]
set_property PACKAGE_PIN L13 [get_ports leds_o[22]]
set_property PACKAGE_PIN K17 [get_ports leds_o[23]]

set_property PACKAGE_PIN R1 [get_ports buttons_i[0]]
set_property PACKAGE_PIN P1 [get_ports buttons_i[1]]
set_property PACKAGE_PIN P5 [get_ports buttons_i[2]]
set_property PACKAGE_PIN P4 [get_ports buttons_i[3]]
set_property PACKAGE_PIN P2 [get_ports buttons_i[4]]












set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led_en[7]]

set_property IOSTANDARD LVCMOS33 [get_ports led_ca_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_cb_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_cc_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_cd_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_ce_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_cf_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_cg_o]
set_property IOSTANDARD LVCMOS33 [get_ports led_dp_o]


set_property IOSTANDARD LVCMOS33 [get_ports switches_i[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[3]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[4]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[5]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[6]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[7]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[8]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[9]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[10]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[11]]
set_property IOSTANDARD LVCMOS33  [get_ports switches_i[12]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[13]]
set_property IOSTANDARD LVCMOS33  [get_ports switches_i[14]]
set_property IOSTANDARD LVCMOS33  [get_ports switches_i[15]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[16]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[17]]
set_property IOSTANDARD LVCMOS33  [get_ports switches_i[18]]
set_property IOSTANDARD LVCMOS33  [get_ports switches_i[19]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[20]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[21]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[22]]
set_property IOSTANDARD LVCMOS33 [get_ports switches_i[23]]

set_property IOSTANDARD LVCMOS33 [get_ports leds_o[0]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[1]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[2]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[3]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[4]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[5]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[6]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[7]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[8]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[9]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[10]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[11]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[12]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[13]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[14]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[15]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[16]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[17]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[18]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[19]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[20]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[21]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[22]]
set_property IOSTANDARD LVCMOS33 [get_ports leds_o[23]]

set_property IOSTANDARD LVCMOS33 [get_ports buttons_i[0]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons_i[1]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons_i[2]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons_i[3]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons_i[4]]